### ISSUE TITLE
Support common image format inputs (JPG/PNG)

### ISSUE THREAD

**Issue by EwoutH** [joedrago/avif#10]
I don't know if it's in the scope of this project, but I would love an avif encoder that can take common image formats as input instead of only 74m. PNG and JPG support would be most relevant, but WebP, Heic, GIF and TIFF would also be useful.

For example, [cwebp](https://developers.google.com/speed/webp/docs/cwebp) supports PNG, JPEG, TIFF, WebP or raw Y'CbCr images. The decode libraries used by libwebp can be found at https://github.com/webmproject/libwebp/tree/master/imageio.

**Comment by joedrago** [comment]
My intent for avifenc and avifdec are merely to provide a simple example and offline tool to make a valid avif files. My main concerns against adding other formats would simply be external dependency bloat, but as long as it was optional in CMake, it miiiiight be okay.

Not to (necessarily) shamelessly plug other projects of mine, but my image conversion tool [colorist](https://joedrago.github.io/colorist/) does precisely what you're asking, for PNG, JPEG, (basic) TIFF, WebP, and JPEG2000. You can not only bidirectionally convert to AVIF with this tool, but you can generate test (SDR or HDR) AVIFs with [image strings](https://github.com/joedrago/colorist/blob/master/docs/Usage.md#image-strings).

I'm much more likely to load colorist up with more formats over time than turn avifenc/avifdec into a general purpose tool. If anything, I'd rather see something like the venerable ImageMagick adopt libavif and then you could really do anything you wanted with avif.

**Comment by EwoutH** [comment]
@joedrago Thanks, Colorist looks like a great tool!

Do you expect any API changes in the near future for libavif?

**Comment by joedrago** [comment]
The short answer is "yes".

The long answer is libavif is still in its infancy, and while it is quite functional, I still have some aom options I'd like to surface in the API, and once some of the AOM team starts auditing these headers, I imagine some of my enums or other features could be altered. I'm also still on the fence on adding image sequences, which would probably be a pretty meaningful breaking change. I'm also probably going to pull out the automatic YUV->RGB step during decode, as it is leading the witness a bit.

Generally speaking though, I'm pleased with the usability of the API (as a user of it), so I hope early adopters won't be _completely_ lost if they have to fix up their code on new versions.
