### ISSUE TITLE
Usage issue ? Always see the stretch and green color for sample AVIF images

### ISSUE THREAD

**Issue by dreampiggy** [joedrago/avif#9]
Hi. Sorry to bother here...

I'm a iOS/macOS developer, but is not expert in Image Decoding and Processing. But recentlly I have interests in AVIF image foramt. And I want to build a simple client-side image viewer, to see the render result of AVIF images.

So I found this project, and using the straight forward code to decode the AVIF images into RGB bitmap buffer. Then using the platform API to show the bitmap buffer on screen.

But, all the tests images I used, will result a `Stretch` and `Green` color of the original image. It's a little strange. Like the following:

+ test image: [av1-avif/still_picture.avif](https://raw.githubusercontent.com/AOMediaCodec/av1-avif/master/testFiles/Microsoft/still_picture.avif)
+ platform: macOS 10.14.4
+ avif (this lib) version: tag `v0.1.0`
+ aom version: Tested with `v1.0.0` and `v1.0.0-errata1`

The render result:

![image](https://user-images.githubusercontent.com/6919743/56082728-b6de6900-5e4e-11e9-9094-993e0da2232b.png)

Actual image:

![image](https://user-images.githubusercontent.com/6919743/56082741-e2615380-5e4e-11e9-8b9b-b2f2aae75921.png)

I wonder, if this is because of my usage issue ? Or something about AVIF spec changes ? Because I also try another AVIF library: [libheif](https://github.com/strukturag/libheif/). Which use aom codec as well to decode HEIF && AVIF images. But sadly, it contains the exact same issue. So I wonder this may be my usage issue 😅

See also: https://github.com/strukturag/libheif/issues/120

**Comment by dreampiggy** [comment]
Code for decoding AVIF using this lib. I'm always preferring using RGB instead of YUV, because the Apple platform High-Level API prefers RGB for easy usage...

```objectivec
static void FillRGBABufferWithAVIFImage(vImage_Buffer *red, vImage_Buffer *green, vImage_Buffer *blue, vImage_Buffer *alpha, avifImage *img) {
    red->width = img->width;
    red->height = img->height;
    red->data = img->rgbPlanes[0];
    red->rowBytes = img->rgbRowBytes[0];
    
    green->width = img->width;
    green->height = img->height;
    green->data = img->rgbPlanes[1];
    green->rowBytes = img->rgbRowBytes[1];
    
    blue->width = img->width;
    blue->height = img->height;
    blue->data = img->rgbPlanes[2];
    blue->rowBytes = img->rgbRowBytes[2];
    
    if (img->alphaPlane) {
        alpha->width = img->width;
        alpha->height = img->height;
        alpha->data = img->alphaPlane;
        alpha->rowBytes = img->alphaRowBytes;
    }
}

- (CGImageRef)createAVIFImageWithData:(NSData *)data {
    // Decode it
    avifRawData raw = {
        .data = data.bytes,
        .size = data.length
    };
    avifImage * img = avifImageCreateEmpty();
    avifResult result = avifImageRead(img, &raw);
    if (result != AVIF_RESULT_OK) {
        avifImageDestroy(img);
        return nil;
    }
    
    int height = img->height;
    int width = img->width;
    int depth = img->depth;
    BOOL hasAlpha = img->alphaPlane != NULL;
    
    vImage_Buffer red, green, blue, alpha;
    FillRGBABufferWithAVIFImage(&red, &green, &blue, &alpha, img);
    
    vImage_Buffer dest;
    vImageBuffer_Init(&dest, height, width, hasAlpha ? 32 : 24, kvImageNoFlags);
    if (!dest.data) {
        return nil;
    }
    
    vImage_Error error = vImageConvert_Planar8toRGB888(&red, &green, &blue, &dest, kvImageNoFlags);
    if (error != kvImageNoError) {
        avifImageDestroy(img);
        free(dest.data);
        return nil;
    }
    
    // Below are Apple's platform API to produce a Bitmap Buffer Image object, used in AppKit API.
    CGDataProviderRef provider =
    CGDataProviderCreateWithData(NULL, dest.data, dest.rowBytes * dest.height, NULL);
    size_t bitsPerComponent = 8;
    size_t bitsPerPixel = hasAlpha ? 32 : 24;
    CGBitmapInfo bitmapInfo = kCGBitmapByteOrder32Big;
    bitmapInfo |= hasAlpha ? kCGImageAlphaLast : kCGImageAlphaNone;
    CGColorSpaceRef colorSpaceRef = [SDImageCoderHelper colorSpaceGetDeviceRGB];
    CGColorRenderingIntent renderingIntent = kCGRenderingIntentDefault;
    CGImageRef imageRef = CGImageCreate(width, height, bitsPerComponent, bitsPerPixel, dest.rowBytes, colorSpaceRef, bitmapInfo, provider, NULL, NO, renderingIntent);
    
    // clean up
    CGDataProviderRelease(provider);
    avifImageDestroy(img);
    free(dest.data);
    
    return imageRef;
}
```

**Comment by joedrago** [comment]
Hello! I don't really know anything about Apple's vImage APIs, but I independently verified that the still_picture image you offered above contains correct information in it. If I use my colorist tool to convert:

colorist convert still_picture.avif still_picture.png

The resultant PNG looks normal:

![still_picture](https://user-images.githubusercontent.com/332342/56083258-55c77e80-5dd7-11e9-990c-7f23326beb0b.png)

If you want to compare notes, this is how I harvest the RGBA values out of a decoded avif (using my library):

https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c#L59

Skimming your code, one random observation is you're using vImageBuffer_Init() to make dest, but not red, green, and blue? Is there a reason for that asymmetry? Could that cause an issue?

**Comment by dreampiggy** [comment]
That [vImageBuffer_Init](https://developer.apple.com/documentation/accelerate/1399064-vimagebuffer_init?language=objc) is just like a convenient alloc for bitmap buffer. I need the interlaced RGB bitmap to using the platform API, instead each of 3 channels. So I also using another call [vImageConvert_Planar8toRGB888](https://developer.apple.com/documentation/accelerate/1533110-vimageconvert_planar8torgb888?language=objc) to convert 3 channnels into RGB. It may be faster than for-in-loop...

I tried your [colorist](https://github.com/joedrago/colorist) tool, it works without any issue.

But sadly, even I change the code like this (from your colorist lib):

```c
    int height = avif->height;
    int width = avif->width;
    int depth = avif->depth;
    BOOL hasAlpha = avif->alphaPlane != NULL;
    
    size_t CL_CHANNELS_PER_PIXEL = hasAlpha ? 4 : 3;
    size_t rowBytes = width * CL_CHANNELS_PER_PIXEL * 8 / 8;
    uint8_t * dest = calloc(width * CL_CHANNELS_PER_PIXEL * height, sizeof(uint8_t));
    
    for (int j = 0; j < avif->height; ++j) {
        for (int i = 0; i < avif->width; ++i) {
            uint8_t *pixel = &dest[CL_CHANNELS_PER_PIXEL * (i + (j * width))];
            pixel[0] = avif->rgbPlanes[AVIF_CHAN_R][i + (j * avif->rgbRowBytes[AVIF_CHAN_R])];
            pixel[1] = avif->rgbPlanes[AVIF_CHAN_G][i + (j * avif->rgbRowBytes[AVIF_CHAN_G])];
            pixel[2] = avif->rgbPlanes[AVIF_CHAN_B][i + (j * avif->rgbRowBytes[AVIF_CHAN_B])];
            if (avif->alphaPlane) {
                pixel[3] = avif->alphaPlane[i + (j * avif->alphaRowBytes)];
            }
        }
    }

    CGDataProviderRef provider = CGDataProviderCreateWithData(NULL, dest, rowBytes * height, NULL);
    // ...
```

Seems still not help. The strange bitmap result is exact the same with `Green` and `Stretch` color 😅

![image](https://user-images.githubusercontent.com/6919743/56082728-b6de6900-5e4e-11e9-9094-993e0da2232b.png) 

I check the AVIF images, does not using 16bit depth and it's 8bit. So I wonder maybe it's not related to convert.

Is that the aom version issue ? Should I use the `master` branch of aom instead the tagged one ?

**Comment by dreampiggy** [comment]
OK...I finally found that it's because of the aom I built. After using cmake of your repo's aom, to build a `libaom.a` and `libaom_version.a`, then get them linked, the issue was gone, without no any line code changes above...

![image](https://user-images.githubusercontent.com/6919743/56088345-78c66100-5eb1-11e9-906e-3aacefe62187.png)

I previously tried with the aom `v1.0.0` from homebrew, See: https://github.com/Homebrew/homebrew-core/blob/master/Formula/aom.rb

But I found it out-of-date. So I built one by cloning the aom repo (https://aomedia.googlesource.com/aom/). Build the tagged `v1.0.0-errata1`.

I don't found any version or CID for your `ext/aom` dependency, could you tell me which of cid you use ? So that I can use the dependency manager to specify a target cid and build it using pipeline.

**Comment by joedrago** [comment]
Ah, yes, that is quite absent from all records here. I'll add it to the ChangeLog so I can keep track of it as I update it (or stop being stubborn and switch it to a submodule). 

Based on my original clone of aom here: 

https://github.com/joedrago/aom/commits/master

It looks like I just added a bit of CMake sugar on top of commit 3563b12b. 

Congrats on getting stuff working! It is nice to see some usage out of the library.

**Comment by joedrago** [comment]
There we go, added it to the [ChangeLog](https://github.com/joedrago/avif/blob/master/CHANGELOG.md). I'll probably make it a proper submodule when I pull all of the latest changes.
